version: "3.9"

services:
    postgres:
        image: pgvector/pgvector:pg16
        container_name: books-postgres
        environment:
            POSTGRES_DB: bookshelf
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./docker/postgres/init:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U laravel -d bookshelf"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    pgdata:
